apiVersion: v1
kind: Service
metadata:
  name: notification-server-service
spec:
  selector:
    app: notification-server
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
  type: NodePort
